services:
  web:
    ports:
      - "3000:3000"
    build: .
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json