import {Funnel_Display} from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const funelDisplay = Funnel_Display({
    subsets: ['latin'],
    weight: ['400']
})

export default function RootLayout({
                                       children
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={funelDisplay.className}>
        <body>
        <header className={"border-b border-white w-full"}>
            <nav className="mx-8 my-4 flex justify-between items-center">
                <Link href="/">
                    <h1 className="text-3xl">Adam Holeček</h1>
                </Link>
                <ul className="flex space-x-6">
                    <li>
                        <Link href="/" className="">Home</Link>
                    </li>
                    <li>
                        <Link href="/contact" className="">Contact me</Link>
                    </li>
                </ul>
            </nav>
        </header>
        {children}
        <footer className={"flex justify-center border-t border-white"}>
            <p>Adam Jiří Holeček</p>
        </footer>
        </body>
        </html>
    );
}
